
server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console